#undef CONTIKIMAC_CONF_SEND_SW_ACK
#define CONTIKIMAC_CONF_SEND_SW_ACK 1

#undef QUEUEBUF_CONF_NUM
#define QUEUEBUF_CONF_NUM 20

// #define UAV 1
#define FFD_OPEN 1
// #define FFD_TELO 1
#if UAV
#undef CONTIKIMAC_CHANNEL_CHANGE
#define CONTIKIMAC_CHANNEL_CHANGE 0

#undef NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE
#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 8

#undef WRITE_TO_FLASH
#define WRITE_TO_FLASH 0

#elif FFD_OPEN
#undef CONTIKIMAC_CHANNEL_CHANGE
#define CONTIKIMAC_CHANNEL_CHANGE 1

#undef NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE
#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 16

#undef WRITE_TO_FLASH
#define WRITE_TO_FLASH 0

#elif FFD_TELO
#undef CONTIKIMAC_CHANNEL_CHANGE
#define CONTIKIMAC_CHANNEL_CHANGE 0

#undef NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE
#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 16

#undef WRITE_TO_FLASH
#define WRITE_TO_FLASH 0

#endif

#define FFD_CHANNEL_1   26      // DRONE_REQU
#define FFD_CHANNEL_2   25      // DRONE_DATA
#define FFD_CHANNEL_3   11      // CH-SENSORS



#undef NEED_FORMATTING
#define NEED_FORMATTING 0

// #define LPM_CONF_ENABLE       1
// #define LPM_CONF_MAX_PM       2

#if CONTIKI_TARGET_OPENMOTE_CC2538 
#define COFFEE_CONF_SIZE              (CC2538_DEV_FLASH_SIZE / 2)
#define COFFEE_CONF_MICRO_LOGS        1
#define COFFEE_CONF_APPEND_ONLY       0
#endif /* CONTIKI_TARGET_OPENMOTE_CC2538 */