#undef CONTIKIMAC_CONF_SEND_SW_ACK
#define CONTIKIMAC_CONF_SEND_SW_ACK 1

#undef QUEUEBUF_CONF_NUM
#define QUEUEBUF_CONF_NUM 20

#undef CONTIKIMAC_CHANNEL_CHANGE
#define CONTIKIMAC_CHANNEL_CHANGE 0

#undef NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE
#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 8

#undef WRITE_TO_FLASH
#define WRITE_TO_FLASH 0

#undef NEED_FORMATTING
#define NEED_FORMATTING 0

#if CONTIKI_TARGET_OPENMOTE_CC2538 
#define COFFEE_CONF_SIZE              (CC2538_DEV_FLASH_SIZE / 2)
#define COFFEE_CONF_MICRO_LOGS        1
#define COFFEE_CONF_APPEND_ONLY       0
#endif /* CONTIKI_TARGET_OPENMOTE_CC2538 */