#undef NEED_FORMATTING
#define NEED_FORMATTING 0

// #define LPM_CONF_ENABLE       1
// #define LPM_CONF_MAX_PM       2

#if CONTIKI_TARGET_OPENMOTE_CC2538 
#define COFFEE_CONF_SIZE              (CC2538_DEV_FLASH_SIZE / 2)
#define COFFEE_CONF_MICRO_LOGS        1
#define COFFEE_CONF_APPEND_ONLY       0
#endif /* CONTIKI_TARGET_OPENMOTE_CC2538 */